services:
  - type: web
    name: gtcc-bot-api
    env: python
    region: singapore # Hoặc oregon, frankfurt tùy bạn
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: LLM_ENGINE
        value: groq
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
